ALTER TABLE votings
  ADD COLUMN IF NOT EXISTS oylama_tipi  VARCHAR(10)  NOT NULL DEFAULT 'gizli',
  ADD COLUMN IF NOT EXISTS esik_tipi    VARCHAR(20)  NOT NULL DEFAULT 'salt_cogunluk',
  ADD COLUMN IF NOT EXISTS esik_sayi    INTEGER      NOT NULL DEFAULT 17,
  ADD COLUMN IF NOT EXISTS toplam_uye   INTEGER      NOT NULL DEFAULT 32;